name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: fractal-output

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Python
        uses: actions/setup-python@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: 3.9

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip
          pip install wheel build
          python -m build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
